- name: create releases directory
  file:
    path: "/opt/apps/employee/releases/{{ employee.release.version }}"
    state: directory
    recurse: yes
    mode: 0755

- name: download release artifact
  unarchive:
    src: "{{ employee.release.url }}"
    dest: "/opt/apps/employee/releases/{{ employee.release.version }}"
    remote_src: yes
    mode: 0755

- name: create relase symlink
  file:
    src: "/opt/apps/employee/releases/{{ employee.release.version }}"
    dest: /opt/employee
    state: link
  notify: restart employee service


- name: copy supervisor config for employee
  copy:
    src: employee.supervisor.conf
    dest: /etc/supervisor/conf.d/employee.conf
    mode: 0755
  notify: restart supervisor

- meta: flush_handlers

- name: start employee service
  supervisorctl:
    name: employee
    state: started
